version: "3.8"
services:
  db:
    container_name: db-fhnw-mysql
    platform: linux/x86_64 #required because of Macbook M1 Pro ARM
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fhnw_mysql
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: sqlpassword
    ports:
      - "3306:3306"
    volumes:
      - db-fhnw-mysql:/var/lib/mysql
volumes:
  db-fhnw-mysql:
